/**
* Generated by LEA for Arma 3
* Version: 2.0.17
* Tue May 13 01:12:47 BST 2014
* Mission file name: Library.Altis - Copy
* Mission name: Library.Altis - Copy
* Required mods:
* + ArmA 3
* 
* Call the script: _dummy = [] execvm "lea\loadoutSingleplayer.sqf";
* 
*/

/**
* Loadout for crates
*/

//Empty, nothing to do. unit chopper
//Empty, nothing to do. unit truck_1
//Empty, nothing to do. unit truck_2
//Empty, nothing to do. unit truck_3
//Empty, nothing to do. unit apc_1
//Empty, nothing to do. unit heli_2
//Empty, nothing to do. unit heli_1
//Empty, nothing to do. unit apc_2
//Empty, nothing to do. unit apc_3
//Empty, nothing to do. unit apc_4

/**
* Loadout for soldiers units
*/

removeallweapons unit_0_0;
removeallassigneditems unit_0_0;
removeHeadgear unit_0_0;
removeUniform unit_0_0;
removeBackpack unit_0_0;
removeVest unit_0_0;

unit_0_0 addBackpack "B_TacticalPack_blk";
(backpackContainer unit_0_0) addmagazinecargoGlobal ["30Rnd_65x39_caseless_green_mag_Tracer",1];
unit_0_0 addWeapon "arifle_Katiba_C_F";
removeBackpack unit_0_0;
unit_0_0 addPrimaryWeaponItem "optic_ACO_grn";
unit_0_0 addBackpack "B_TacticalPack_blk";
(backpackContainer unit_0_0) addmagazinecargoGlobal ["16Rnd_9x21_Mag",1];
unit_0_0 addWeapon "hgun_P07_F";
removeBackpack unit_0_0;
unit_0_0 addHandgunItem "muzzle_snds_L";
unit_0_0 addBackpack "B_TacticalPack_ocamo";
clearItemCargoGlobal (backpackContainer unit_0_0);
clearMagazineCargoGlobal (backpackContainer unit_0_0);
clearWeaponCargoGlobal (backpackContainer unit_0_0);
unit_0_0 addVest "V_Chestrig_khk";
clearItemCargoGlobal (vestContainer unit_0_0);
clearMagazineCargoGlobal (vestContainer unit_0_0);
clearWeaponCargoGlobal (vestContainer unit_0_0);
(vestContainer unit_0_0) addmagazinecargoGlobal ["30Rnd_65x39_caseless_green",2];
unit_0_0 addUniform "U_B_CombatUniform_mcam_tshirt";
clearItemCargoGlobal (uniformContainer unit_0_0);
clearMagazineCargoGlobal (uniformContainer unit_0_0);
clearWeaponCargoGlobal (uniformContainer unit_0_0);
unit_0_0 selectWeapon (primaryWeapon unit_0_0);

removeallweapons the_squad;
removeallassigneditems the_squad;
removeHeadgear the_squad;
removeUniform the_squad;
removeBackpack the_squad;
removeVest the_squad;

if (count weapons the_squad > 0) then {
  private['_type', '_muzzles'];
  _type = ((weapons the_squad) select 0);
  _muzzles = getArray(configFile >>"cfgWeapons">> _type >>"muzzles");
  if (count _muzzles > 1) then {
     the_squad selectWeapon (_muzzles select 0);
  }
  else {
     the_squad selectWeapon _type;
  };
};

removeallweapons squad1;
removeallassigneditems squad1;
removeHeadgear squad1;
removeUniform squad1;
removeBackpack squad1;
removeVest squad1;

if (count weapons squad1 > 0) then {
  private['_type', '_muzzles'];
  _type = ((weapons squad1) select 0);
  _muzzles = getArray(configFile >>"cfgWeapons">> _type >>"muzzles");
  if (count _muzzles > 1) then {
     squad1 selectWeapon (_muzzles select 0);
  }
  else {
     squad1 selectWeapon _type;
  };
};

removeallweapons com3_1_1;
removeallassigneditems com3_1_1;
removeHeadgear com3_1_1;
removeUniform com3_1_1;
removeBackpack com3_1_1;
removeVest com3_1_1;

if (count weapons com3_1_1 > 0) then {
  private['_type', '_muzzles'];
  _type = ((weapons com3_1_1) select 0);
  _muzzles = getArray(configFile >>"cfgWeapons">> _type >>"muzzles");
  if (count _muzzles > 1) then {
     com3_1_1 selectWeapon (_muzzles select 0);
  }
  else {
     com3_1_1 selectWeapon _type;
  };
};

removeallweapons com5_1;
removeallassigneditems com5_1;
removeHeadgear com5_1;
removeUniform com5_1;
removeBackpack com5_1;
removeVest com5_1;

if (count weapons com5_1 > 0) then {
  private['_type', '_muzzles'];
  _type = ((weapons com5_1) select 0);
  _muzzles = getArray(configFile >>"cfgWeapons">> _type >>"muzzles");
  if (count _muzzles > 1) then {
     com5_1 selectWeapon (_muzzles select 0);
  }
  else {
     com5_1 selectWeapon _type;
  };
};

removeallweapons com7_1;
removeallassigneditems com7_1;
removeHeadgear com7_1;
removeUniform com7_1;
removeBackpack com7_1;
removeVest com7_1;

if (count weapons com7_1 > 0) then {
  private['_type', '_muzzles'];
  _type = ((weapons com7_1) select 0);
  _muzzles = getArray(configFile >>"cfgWeapons">> _type >>"muzzles");
  if (count _muzzles > 1) then {
     com7_1 selectWeapon (_muzzles select 0);
  }
  else {
     com7_1 selectWeapon _type;
  };
};

removeallweapons com6_1;
removeallassigneditems com6_1;
removeHeadgear com6_1;
removeUniform com6_1;
removeBackpack com6_1;
removeVest com6_1;

if (count weapons com6_1 > 0) then {
  private['_type', '_muzzles'];
  _type = ((weapons com6_1) select 0);
  _muzzles = getArray(configFile >>"cfgWeapons">> _type >>"muzzles");
  if (count _muzzles > 1) then {
     com6_1 selectWeapon (_muzzles select 0);
  }
  else {
     com6_1 selectWeapon _type;
  };
};

removeallweapons com3_1;
removeallassigneditems com3_1;
removeHeadgear com3_1;
removeUniform com3_1;
removeBackpack com3_1;
removeVest com3_1;

if (count weapons com3_1 > 0) then {
  private['_type', '_muzzles'];
  _type = ((weapons com3_1) select 0);
  _muzzles = getArray(configFile >>"cfgWeapons">> _type >>"muzzles");
  if (count _muzzles > 1) then {
     com3_1 selectWeapon (_muzzles select 0);
  }
  else {
     com3_1 selectWeapon _type;
  };
};

removeallweapons com4_1;
removeallassigneditems com4_1;
removeHeadgear com4_1;
removeUniform com4_1;
removeBackpack com4_1;
removeVest com4_1;

if (count weapons com4_1 > 0) then {
  private['_type', '_muzzles'];
  _type = ((weapons com4_1) select 0);
  _muzzles = getArray(configFile >>"cfgWeapons">> _type >>"muzzles");
  if (count _muzzles > 1) then {
     com4_1 selectWeapon (_muzzles select 0);
  }
  else {
     com4_1 selectWeapon _type;
  };
};

removeallweapons com2_1;
removeallassigneditems com2_1;
removeHeadgear com2_1;
removeUniform com2_1;
removeBackpack com2_1;
removeVest com2_1;

if (count weapons com2_1 > 0) then {
  private['_type', '_muzzles'];
  _type = ((weapons com2_1) select 0);
  _muzzles = getArray(configFile >>"cfgWeapons">> _type >>"muzzles");
  if (count _muzzles > 1) then {
     com2_1 selectWeapon (_muzzles select 0);
  }
  else {
     com2_1 selectWeapon _type;
  };
};

removeallweapons squad_leader;
removeallassigneditems squad_leader;
removeHeadgear squad_leader;
removeUniform squad_leader;
removeBackpack squad_leader;
removeVest squad_leader;

if (count weapons squad_leader > 0) then {
  private['_type', '_muzzles'];
  _type = ((weapons squad_leader) select 0);
  _muzzles = getArray(configFile >>"cfgWeapons">> _type >>"muzzles");
  if (count _muzzles > 1) then {
     squad_leader selectWeapon (_muzzles select 0);
  }
  else {
     squad_leader selectWeapon _type;
  };
};

removeallweapons reinf_1;
removeallassigneditems reinf_1;
removeHeadgear reinf_1;
removeUniform reinf_1;
removeBackpack reinf_1;
removeVest reinf_1;

if (count weapons reinf_1 > 0) then {
  private['_type', '_muzzles'];
  _type = ((weapons reinf_1) select 0);
  _muzzles = getArray(configFile >>"cfgWeapons">> _type >>"muzzles");
  if (count _muzzles > 1) then {
     reinf_1 selectWeapon (_muzzles select 0);
  }
  else {
     reinf_1 selectWeapon _type;
  };
};

removeallweapons reinf_3;
removeallassigneditems reinf_3;
removeHeadgear reinf_3;
removeUniform reinf_3;
removeBackpack reinf_3;
removeVest reinf_3;

if (count weapons reinf_3 > 0) then {
  private['_type', '_muzzles'];
  _type = ((weapons reinf_3) select 0);
  _muzzles = getArray(configFile >>"cfgWeapons">> _type >>"muzzles");
  if (count _muzzles > 1) then {
     reinf_3 selectWeapon (_muzzles select 0);
  }
  else {
     reinf_3 selectWeapon _type;
  };
};

removeallweapons reinf_2;
removeallassigneditems reinf_2;
removeHeadgear reinf_2;
removeUniform reinf_2;
removeBackpack reinf_2;
removeVest reinf_2;

if (count weapons reinf_2 > 0) then {
  private['_type', '_muzzles'];
  _type = ((weapons reinf_2) select 0);
  _muzzles = getArray(configFile >>"cfgWeapons">> _type >>"muzzles");
  if (count _muzzles > 1) then {
     reinf_2 selectWeapon (_muzzles select 0);
  }
  else {
     reinf_2 selectWeapon _type;
  };
};

removeallweapons reinf_6;
removeallassigneditems reinf_6;
removeHeadgear reinf_6;
removeUniform reinf_6;
removeBackpack reinf_6;
removeVest reinf_6;

if (count weapons reinf_6 > 0) then {
  private['_type', '_muzzles'];
  _type = ((weapons reinf_6) select 0);
  _muzzles = getArray(configFile >>"cfgWeapons">> _type >>"muzzles");
  if (count _muzzles > 1) then {
     reinf_6 selectWeapon (_muzzles select 0);
  }
  else {
     reinf_6 selectWeapon _type;
  };
};

removeallweapons reinf_4;
removeallassigneditems reinf_4;
removeHeadgear reinf_4;
removeUniform reinf_4;
removeBackpack reinf_4;
removeVest reinf_4;

if (count weapons reinf_4 > 0) then {
  private['_type', '_muzzles'];
  _type = ((weapons reinf_4) select 0);
  _muzzles = getArray(configFile >>"cfgWeapons">> _type >>"muzzles");
  if (count _muzzles > 1) then {
     reinf_4 selectWeapon (_muzzles select 0);
  }
  else {
     reinf_4 selectWeapon _type;
  };
};

removeallweapons reinf_5;
removeallassigneditems reinf_5;
removeHeadgear reinf_5;
removeUniform reinf_5;
removeBackpack reinf_5;
removeVest reinf_5;

if (count weapons reinf_5 > 0) then {
  private['_type', '_muzzles'];
  _type = ((weapons reinf_5) select 0);
  _muzzles = getArray(configFile >>"cfgWeapons">> _type >>"muzzles");
  if (count _muzzles > 1) then {
     reinf_5 selectWeapon (_muzzles select 0);
  }
  else {
     reinf_5 selectWeapon _type;
  };
};

removeallweapons reinf_7;
removeallassigneditems reinf_7;
removeHeadgear reinf_7;
removeUniform reinf_7;
removeBackpack reinf_7;
removeVest reinf_7;

if (count weapons reinf_7 > 0) then {
  private['_type', '_muzzles'];
  _type = ((weapons reinf_7) select 0);
  _muzzles = getArray(configFile >>"cfgWeapons">> _type >>"muzzles");
  if (count _muzzles > 1) then {
     reinf_7 selectWeapon (_muzzles select 0);
  }
  else {
     reinf_7 selectWeapon _type;
  };
};

removeallweapons reinf_8;
removeallassigneditems reinf_8;
removeHeadgear reinf_8;
removeUniform reinf_8;
removeBackpack reinf_8;
removeVest reinf_8;

if (count weapons reinf_8 > 0) then {
  private['_type', '_muzzles'];
  _type = ((weapons reinf_8) select 0);
  _muzzles = getArray(configFile >>"cfgWeapons">> _type >>"muzzles");
  if (count _muzzles > 1) then {
     reinf_8 selectWeapon (_muzzles select 0);
  }
  else {
     reinf_8 selectWeapon _type;
  };
};

